### ISSUE TITLE
Error after blob copy that the storage account exists

### ISSUE THREAD

**Issue by recintoit** [Azure/migAz#164]
Hello,
I was successful a few months ago on 2.3.0.1.  During this new run, I put in suffixes in Options for the  storage account to have 'v2'.  After the blob copy the next step stopped the process with this error (it's like it is trying create the storage account again?):  

ew-AzureRmResourceGroupDeployment : 8:47:11 PM - Resource Microsoft.Storage/storageAccounts 'davlmigazpremv2' failed with message '{
  "error": {
    "code": "StorageAccountAlreadyExists",
    "message": "The storage account named davlmigazpremv2 already exists under the subscription."
  }
}'
At C:\Users\myname\Documents\Azure\Migration\MigAzv2.4.2.1\MigAz.ps1:281 char:3
+         New-AzureRmResourceGroupDeployment -ResourceGroupName $Resour ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

**Comment by rsanderson2350** [comment]
Do you have Visual Studio 2017, or are you only running compiled released?  Am I correct that you are migrating VMs targeting Classic Disks (not Managed Disks)?  

The current MigAz code branch does already have a change included for this.  The issue occurs because the MigAz.ps1 now handles all needed creation of Storage Accounts.  In turn, because these Storage Accounts also exist as part of the JSON template for resource group deployment, the deployment errors with condition that they already exist.

You may manually modify the JSON Template, by removing the Storage Account definition as well as any references to these Storage Accounts from the Virtual Machine's "DependsOn" section.  

As mentioned this change is available in the current source code by doing a fetch/sync.  If you are dependent upon using the compiled version we can likely do a compiled release (not aware of any major breaking issues in the current code available).

**Comment by recintoit** [comment]
Thanks for the quick response.  I’m running the compiles release.  I
figured it was in the JSON, but didn’t know which to edit.    The error
pointed to the .ps1, but when went to line 298 it was the if/else logic to
stop.

I’ll try again tonight (on one VM) with the edit to the JSON and VM depends
on.  I’m planning on migrating our dev and test environments soon.  So by
the time I ge to stage and Prod, I’m sure you will have a new compiled
release

Thanks again,
Mike

**Comment by rsanderson2350** [comment]
Ok, I'll go ahead and publish a new release (we have had a couple of people using it, and I think the major breaks are resolved in the recent code restructure).  Look for an updated build tonight.  You can also compare JSON Templates between the old and new release, but you'll observe the Storage Accounts are not placed into the JSON file and likewise, they are not referenced in the "DependsOn" section of the Virtual Machine(s).

Thanks!

**Comment by rsanderson2350** [comment]
Release completed, please advise if you find your issue resolved with v2.4.2.2.  Thanks!

**Comment by recintoit** [comment]
Hi!

I downloaded the compiled release but I have a different error that I never
had during the export phase.  I can't continue because the Datadisk on my
VM is requiring a LUN.  I could probably find that in the Portal, but in
the previous versions I never had to specify a LUN.
I'm going from unmanaged disk to unmanaged disk at this time.  Below is the
screenshot


Thanks,

**Comment by rsanderson2350** [comment]
Ok, let me do a quick test on Unmanaged Disks for getting the existing LUN.

**Comment by recintoit** [comment]
Hi,

were you able to recreate the issue I'm seeing?  I ran the same selections
on 2.4.2.1 and I notices that LUN selection appears where the highlight  is
in the new version.  It is not there in the previous.



Thanks,

**Comment by rsanderson2350** [comment]
Closing issue, based on issue scope/discussion/resolution on storage account already existing.  LUN selection issue discussed in Issue #166 .
