### ISSUE TITLE
acceleratedNetworking API-Version mismatch

### ISSUE THREAD

**Issue by swieder** [Azure/migAz#193]
Received error in PowerShell when deploying JSON file when migrating a VM from Classic to ARM and selecting Accelerated Networking on target VM:

"Specified api-version 2015-06-15 does not meet the minimum required api-version 2016-09-01 to set this property acceleratedNetworking."

Changing the API version in .json file resolved issue and rerunning successfully deployed new ARM VM.

Changed from:

"type": "Microsoft.Network/networkInterfaces",
      "apiVersion": "**_2015-06-15_**",

to: 

"type": "Microsoft.Network/networkInterfaces",
      "apiVersion": "**_2017-10-01_**",

2017-10-01 was current API version I saw in docs.microsoft.com.....

**Comment by rsanderson2350** [comment]
I will look to resolve this in the tool in the next couple of days.  You are correct that your immediate/temporary resolution is to update the API Version in the JSON Template.  The MigAz Tool has historically always had "fixed" API Versions contained within the JSON output, which it still does today.  The tool now has awareness of the API Versions that are supported by the target environment.  I'll get this upgraded so that the JSON output can now dynamically target these API Versions (target environment based) rather than operating off of fixed API Versions for template generation.  Thanks!

**Comment by swieder** [comment]
Thank you for the quick response!!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by rsanderson2350** [comment]
API Version dropdown now available in v2.4.3.0

**Comment by swieder** [comment]
Nice, will check it out.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
