### ISSUE TITLE
How to improve the VHD copy performance across regions

### ISSUE THREAD

**Issue by chenxin21cn** [Azure/migAz#214]
Hi,
I want to use MigAz to migrate VM across Azure regions . But I found that  Start-AzureStorageBlobCopy  command's performance is not good (around 40 MB/s from China East to China East2 in my case). How can we improve the VHD copy performance? Can we use azcopy tool in MigAz to improve the copy performance?
Thanks

**Comment by ruandersMSFT** [comment]
Yes.  The MigAz tool currently only has built in capability to conduct asynchronous copy, as performed by Start-AzureStorageBlobCopy.  Referring to [Azure Storage Performance and Scalability](https://docs.microsoft.com/en-us/azure/storage/common/storage-performance-checklist#blobs) (see subsection _Copy Blob_), there is no _time guarantee_ for when the blob copy will complete.  Additionally, faster copy performance (non-asynchronous download then upload) can be gained by executing from a VM within the same Azure Location (ensure VM is within same source/target Azure Location to avoid ingress/egress, otherwise ingress/egress charges will apply).

I have considered adding [AzCopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy) references into the PowerShell code to facilitate this type of transfer.  I'll see if I can get that completed in the next day or two.
