### ISSUE TITLE
Public IP Addresses not visible

### ISSUE THREAD

**Issue by richardajyoung** [Azure/migAz#48]
Hi,

The tool cannot see source Public IP addresses (either dynamic or static), when migrating ARM-to-ARM.

This then flows onto issues migrating Load Balancers as they are missing the IP configuration information

Error:Load Balancer must have a FrontEndIpConfiguration.

Outside of that, the tool is awesome!

Cheers

Richard

**Comment by rsanderson2350** [comment]
@richardajyoung Hey Richard, Yes, I could see that occurring, as ASM to ARM Load Balancers and Public IPs were integrated into the last build, but ARM to ARM of both Load Balancers and Public IPs needs to be done.  I am prepping the next code release to help merge AWS in now, and should be able to get that ARM to ARM Load Balaner and Public IP conversion into this build.  Glad the tool is otherwise awesomeness! :)

**Comment by rsanderson2350** [comment]
Version 2.2.4.0 is pending pull request, but I didn't have the time available to work on this yet.  I'll work on it today or tomorrow and update with a 2.2.5.0 release.

**Comment by icebrian** [comment]
I seem to be experiencing the same issue with v2.2.7.0. The tools sees the Public IP address (in use by VM NICs), they are selected and also shown in the Target window, but the generated JSON template does not include the Public IP, whether they are Dynamic or Static.

Also would however like to congratulate dev's on tools, which is absolutely amazing work! Thanks! :)

**Comment by rcarmo** [comment]
Well, on a run today the Public IP addresses were correctly exported in the ARM template, but none of the ones associated to VMs were re-bound to them. Only load balancers were re-created successfully with their public IPs in place.

**Comment by rsanderson2350** [comment]
@rcarmo Should be resolved with the latest v2.2.11.0 build.  Please advise if you still see the issue occurring or if it is resolved.  Thanks.
