### ISSUE TITLE
can we run the copy blob script first then run the template deployment. ?

### ISSUE THREAD

**Issue by adityakumar60** [Azure/migAz#64]
can we run the copy blob script first then run the template deployment.

so that vm's will be able to find the underline blobs, so will not give errors that blob not found and there will not be any need to [re-run](url) the deployment template again

**Comment by rsanderson2350** [comment]
Based on the original and current design of the tool, that can't be done.  The reasoning is that the export.json needs to be run first so that any new target storage accounts are created, then the blob copy can occur successfully and then a re-deployment of export.json is able to complete (find the target disk files).  

I have considered generating a separate json file that is just the storage accounts so that could be run first (successfully without VM creation failure due to missing blobs), blob copy could occur and then a secondary json file could be run that completes all the other provisioning (again successfully without error the fist time, as the blobs would already exist).  

Will have to see about pursuing this change.  Shouldn't be too hard to implement.

**Comment by adityakumar60** [comment]
Thank you very much for explanation, If I am copying the blobs into
existing storage account and in existing resouce group then can I run the
blob copy script first ?

**Comment by rsanderson2350** [comment]
The answer should be yes.  The only purpose for running the resource group deployment with export.json prior to starting and monitoring the blob copy was to create any new storage accounts.  This is being broken out to a separate storageaccounts.json file shortly, and you'll see it is only use if there is one or more new storage accounts.  If there are no new storage accounts, you would just start and monitor the blob copy, then deploy export.json.
